### ISSUE TITLE
Unable to unzip a file from an archive within any simulator based on 64 bit architecture

### ISSUE THREAD

**Issue by Gauleiter** [gianlucabertani/Objective-Zip#37] opened 2015-11-02 18:06 UTC
Zip archive is created (with password) with different archivers and with different content for test reasons, the result is the same and is always reproducible.
Everything is fine on all the simulators but iPad Air (no difference which iOS is setup). Device seems to work well too.
In method 'readDataWithBuffer:'  a line 'int err= unzReadCurrentFile(_unzFile...' always gets as a return value '-3', which is 'Z_DATA_ERROR' and 'msg' contains a string "invalid distance too far back".

Version: objective-zip 1.0.2 (installed as a Pod)
Xcode Version 7.0.1.

**Comment by iKorich** [comment] 2015-11-06 15:36
I have same issue on mac os project
on Mac OS 10.11

**Comment by BMinas** [comment] 2016-02-13 02:18
I also have this issue.  Xcode 7.2.1 fails with iPhone 5s simulator but works with iPhone 4s simulator.  Is there something different between each simulator?  I also installed 1.0.2 as a Pod.  I'm open to any suggestions for debugging this.

**Comment by BMinas** [comment] 2016-02-14 02:10
It seems to be a 32bit vs 64bit issue.  I have a zip file with just one file and a password.  It works on the simulators that *I think* are 32bit.  If I provide a zip file without a password, then it seems to work.

**Comment by Gauleiter** [comment] 2016-08-28 16:43
@gianlucabertani So is there at least any workaround? This thing really blocks app testing for any 64bit simulator

**Comment by gianlucabertani** [comment] 2016-08-28 17:17
I'm afraid I don't have the time to investigate a problem with lower level libraries. What I can suggest is:

* Some forks use the system's zlib as a static library dependency, instead of compiling the sources. Usually it is some versions behind (this is why I prefer the sources), but it may contain custom fixes. So, try forking and using the system's zlib, or look for a fork that already does.
* If it still doesn't work, the ideal solution would be to contact the developer of MiniZip library (@nmoinvaz). He can surely be of more help than me.

**Comment by BMinas** [comment] 2016-08-28 18:39
It's been awhile since I looked at this.  I'm pretty sure that the problem is fixed in MiniZip.  You should be able to just pull the most recent version of MiniZip and the problem goes away.  It would be fairly easy to test.  I might have some time at the end of this week to look at it.

**Comment by gianlucabertani** [comment] 2016-08-28 20:20
Don't know man, replacing its files with those from [github.com/nmoinvaz/minizip](https://github.com/nmoinvaz/minizip) spawns a total of 23 issues, including uninitialized variables, unsafe conversion and a possible null dereference. It looks like a big step back to me.

**Comment by Gauleiter** [comment] 2016-08-28 20:38
Ok, guys, thanks a lot. I'll take a look at this from MiniZip point of view.

**Comment by nmoinvaz** [comment] 2016-08-29 04:16
The issue existed in the official builds of minizip for a long time. I had users contact me a while back and fixed it in my repository. Here is the direct issue:

https://github.com/nmoinvaz/minizip/issues/45
https://github.com/nmoinvaz/minizip/commit/58921f6b960975f0f5a19e990615c8cc6204e47a

If anybody is willing to submit the 23 issues as a pull request I will incorporate.
Thanks.

**Comment by Gauleiter** [comment] 2016-09-02 13:41
I played a bit with the latest 'minizip' version and managed to make my project work well on any simulator with it. All the issues I experienced were 'implicit type cast' warnings. I personally wouldn't consider them as the serious ones, because in most cases they just claim about 'long to integer' (and vice versa) casting loss for the cases, where integer is enough (e.g. hard drive order index). This could be fixed with a refactoring throughout the entire minizip project and a proper quality testing (to avoid type casts entirely); OR it could be done with just a bunch of explicit casts instead of implicit ones to silence the compiler. If the latter one is the case then I can prepare a proper PR. @nmoinvaz @gianlucabertani what do you think?

**Comment by gianlucabertani** [comment] 2016-10-03 07:40
Ok, I'll do as soon as I can dedicate some time to the project.

**Comment by gianlucabertani** [comment] 2017-05-13 14:47
MiniZip updated.

**Closed by gianlucabertani** 2017-05-13 14:47 UTC

**Comment by gianlucabertani** [comment] 2017-05-21 08:38
I've added a new section on README on adding files with encryption. If you're still having doubts, please have a look.

**Comment by Gauleiter** [comment] 2017-06-18 16:50
Great, no I can confirm it's working with any architecture (though at first I had some troubles with the case described in #61, thinking it was still it).
